// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0Vvab1Z80QwKofYhHqo3MGcnh39AKrUc',
    appId: '1:95137890640:web:07ce85e2ec58f36991ac55',
    messagingSenderId: '95137890640',
    projectId: 'arrivo-location-app',
    authDomain: 'arrivo-location-app.firebaseapp.com',
    storageBucket: 'arrivo-location-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOwKlhFpzLidu2gvVL7aOyKcDzFJPoaB8',
    appId: '1:95137890640:android:0325a6caae654c0a91ac55',
    messagingSenderId: '95137890640',
    projectId: 'arrivo-location-app',
    storageBucket: 'arrivo-location-app.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzVMHBbPlRVe0lFUxFvn0Uo54OEATkAWw',
    appId: '1:95137890640:ios:e2513fb540b4441291ac55',
    messagingSenderId: '95137890640',
    projectId: 'arrivo-location-app',
    storageBucket: 'arrivo-location-app.firebasestorage.app',
    iosBundleId: 'com.example.arrivo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzVMHBbPlRVe0lFUxFvn0Uo54OEATkAWw',
    appId: '1:95137890640:ios:e2513fb540b4441291ac55',
    messagingSenderId: '95137890640',
    projectId: 'arrivo-location-app',
    storageBucket: 'arrivo-location-app.firebasestorage.app',
    iosBundleId: 'com.example.arrivo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0Vvab1Z80QwKofYhHqo3MGcnh39AKrUc',
    appId: '1:95137890640:web:b268c8078ea8cce291ac55',
    messagingSenderId: '95137890640',
    projectId: 'arrivo-location-app',
    authDomain: 'arrivo-location-app.firebaseapp.com',
    storageBucket: 'arrivo-location-app.firebasestorage.app',
  );
}
